"""update recipe field into Recipes table

Revision ID: 16368db11b62
Revises: 54917917c4aa
Create Date: 2022-05-17 19:43:22.385045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16368db11b62'
down_revision = '54917917c4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
