"""create Recipes table

Revision ID: 54917917c4aa
Revises: f052b65d561b
Create Date: 2022-05-17 17:45:11.984610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54917917c4aa'
down_revision = 'f052b65d561b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingridients', sa.String(length=1500), nullable=False),
    sa.Column('cooking_type', sa.String(length=80), nullable=False),
    sa.Column('recipe', sa.String(length=2000), nullable=False),
    sa.Column('dish_type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
