"""create two fitnes table

Revision ID: a088f51b7870
Revises: e60bbfd33424
Create Date: 2022-05-20 16:39:05.087381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a088f51b7870'
down_revision = 'e60bbfd33424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitnes_1',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=False),
    sa.Column('equipment', sa.String(length=400), nullable=False),
    sa.Column('gif_url', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('fitnes_2',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=False),
    sa.Column('equipment', sa.String(length=400), nullable=False),
    sa.Column('gif_url', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fitnes_2')
    op.drop_table('fitnes_1')
    # ### end Alembic commands ###
