"""second update recipe field into Recipes table

Revision ID: e60bbfd33424
Revises: 16368db11b62
Create Date: 2022-05-17 19:44:24.253709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60bbfd33424'
down_revision = '16368db11b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe', sa.String(length=8000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'recipe')
    # ### end Alembic commands ###
